### ISSUE TITLE
Can't open project in Monodevelop

### ISSUE THREAD

**Issue by fedeb95** [Dolfik1/Funogram#1]
I forked the repository and tried to open the solution with monodevelop, and appeared the attached message. Using mono 5.0.0

![istantanea - 24052017 - 12 02 42](https://cloud.githubusercontent.com/assets/25415908/26398155/eb956a54-4078-11e7-8a7f-4beae28661ba.png)

**Comment by Dolfik1** [comment]
For now, library targeted only with .Net Core and .Net Standard 1.6, i'll try to add .Net Framework support later.
Library not ready to use, because it's still in development, and some functions, can be changed in finally version.

**Comment by fedeb95** [comment]
Yes, I noticed it's still under development. I wanted to import it and try to develop it further, maybe making pull requests or simply use it as it is now. Guess I'll wait for support, thank you

**Comment by Dolfik1** [comment]
> Yes, I noticed it's still under development. I wanted to import it and try to develop it further, maybe making pull requests or simply use it as it is now. Guess I'll wait for support, thank you
You can use Visual Studio Code with Ionide plugin, it work's fine with F# and .Net Core.

**Comment by Dolfik1** [comment]
MonoDevelop is deprecated, you should use VSCode, Visual Studio, or Rider
