### ISSUE TITLE
Unable to cast object of type 'Newtonsoft.Json.Serialization.JsonPrimitiveContract' to type 'Newtonsoft.Json.Serialization.JsonObjectContract'.'

### ISSUE THREAD

**Issue by dohly** [Dolfik1/Funogram#15]
![default](https://user-images.githubusercontent.com/1271285/52744150-b451c580-2ffd-11e9-9208-8e6ff05bb1cb.png)

Today I downloaded the latest sources and found this issue.
Repro steps:
Send inline keyboard
Then modify message using Api.editMessageTextBase
`Api.editMessageTextBase
                     (Some(q.Message.Value.Chat.Id|>ChatId.Int)) 
                     (Some(q.Message.Value.MessageId))
                     None
                     "Updated"
                     None
                     None
                     (Some(kb))`

**Comment by Dolfik1** [comment]
This case is covered by unit tests and they executed without any errors. Can you make minimal repro code?

**Comment by dohly** [comment]
Yes, sure. 

[I've just slightly modified your testbot app](https://gist.github.com/dohly/1afa4ae783d874e20a8ac5fee7015989)
Steps: 

1. send "/send_message7" command to show inline keyboard
2. press inline button
3. keyboard updated (yahooo)
4. But then I see exception in VS

![1](https://user-images.githubusercontent.com/1271285/52769498-47b4e600-3052-11e9-8ebc-fac39a104664.gif)

Thank you!
