### ISSUE TITLE
Async update handlers

### ISSUE THREAD

**Issue by BadgerTheAdger** [Dolfik1/Funogram#22]
Hey / Hi, can you please allow async update handlers ? 

As of now I need to write this:

startBot { defaultConfig with Token = "token" } (onUpdate >> Async.RunSynchronously) Option.None

It would be very cool if you made it also work with functions returning Async<'t>

**Comment by Dolfik1** [comment]
Hi. You can use `Async.Start` instead `Async.RunSynchronously`

**Comment by BadgerTheAdger** [comment]
Ok, but is it gonna be like a fire-and-forget function then?
I don't want it to be fire-and-forget because I want to make sure all errors are handled etc etc
Or I don't need to worry about it?

**Comment by Dolfik1** [comment]
You should handle all errors in update function by yourself. Otherwise, the bot will crash with the exception

**Comment by BadgerTheAdger** [comment]
https://github.com/Dolfik1/Funogram/blob/master/src/Funogram.Telegram/Bot.fs#L81

But here I've found a code that handles internal errors by printing their details in console

Or you mean that it's not gonna work with Async.Start i.e it will crash if an exception is thrown in a background thread?  

Also I've found a code that seems to be pretty easy to be adjusted to async update handlers: 

https://github.com/Dolfik1/Funogram/blob/master/src/Funogram.Telegram/Bot.fs#L73

I guess simply changing that to do! would do the trick, wouldn't it (just curious)?

**Comment by Dolfik1** [comment]
I'm sorry for late reply.



> But here I've found a code that handles internal errors by printing their details in console:

I've changed this behavior in 2.0.3 version. At this moment you can configure error handler with `OnError` field in config.

Let me explain Funogram's idea. Funogram have basic Telegram types and server-interaction code and this enough to build any bots you want. But we also have `Funogram.Bot` module to allow developers write bots as quickly as possible and do not think about fetching updates, parsing commands etc. So I think that in most cases developers do not want to wait when command will fully processed before fetch new updates.
