### ISSUE TITLE
get notified via webhooks

### ISSUE THREAD

**Issue by BadgerTheAdger** [Dolfik1/Funogram#23]
Hey / Hi once again, so I am currently long-polling telegram API, it would be much better for me and for telegram in terms of resource usage to use webhook / callback mechanism

Sorry have other things to do I don't have enough time to implement it myself so just leaving it here if anybody wants to contribute, this is what I find must-have

**Comment by BadgerTheAdger** [comment]
Seems like that's what "ApiEndpointUrl" in BotConfig class is for.

**Comment by BadgerTheAdger** [comment]
Oh no, it's not. It's something internal - it's the URL by which the bot polls the data.

**Comment by Dolfik1** [comment]
Hi. I have plans to add webhooks support in Funogram soon

**Comment by Dolfik1** [comment]
Funogram support webhooks from 2.0.3 version (#29)
