### ISSUE TITLE
Get rid of .NET Framework target

### ISSUE THREAD

**Issue by gsomix** [Dolfik1/Funogram#25]

**Comment by ForNeVeR** [comment]
Should we really? @Dolfik1, what are your thoughts?

@gsomix, is there any technical motivations for us to do so? E.g. will any new tech be unblocked by getting rid of `net45`?

**Comment by Dolfik1** [comment]
I've removed .NET Framework target because it broke CI build :) I think .NET Framework target is redundant at this moment
