### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by gsomix** [Dolfik1/Funogram#26]
Funogram silently prints exception messages from bot to stdout. It's not reliable error handling strategy, so need to be fixed. It possibly would be a breaking change.
 
https://github.com/Dolfik1/Funogram/blob/master/src/Funogram.Telegram/Bot.fs#L80-L82

**Comment by ForNeVeR** [comment]
A branch-independent link to the code would be https://github.com/Dolfik1/Funogram/blob/1115081e16ad0e390da00f1ef7569404e93bdb97/src/Funogram.Telegram/Bot.fs#L80-L82

(which also gets rendered nicely by GitHub)

Regarding the issue itself, I suggest we add an optional API to process these errors. For example, we could pass an optional `errorHandler` via `config`, and process the exceptions like so:
```fsharp
            with ex ->
                match config.errorHandler with
                | Some handler -> handler ex
                | None ->
                    printfn "Internal error: %s" ex.Message
                return! loopAsync (offset + 1L)
```

We could also go further and allow the handler to terminate the bot process. E.g. something like this:
```fsharp
            with ex ->
                let handler = 
                    config.errorHandler
                    |> Option.defaultValue (fun ex loopAsync offset ->
                        printfn "Internal error: %s" ex.Message
                        loopAsync (offset + 1L))
                return! handler ex loopAsync offset
```

This way, handler will have the choice to either call `loopAsync` passed to it, or terminate the whole workflow. Also, if the handler in question is optional, then it's not a breaking change.

**Comment by Dolfik1** [comment]
I have improved error handling in #29
