### ISSUE TITLE
Telegram.Api.answerInlineQueryBase has an invalid signature

### ISSUE THREAD

**Issue by alienmonsterrus** [Dolfik1/Funogram#27]
In official [documentation](https://core.telegram.org/bots/api#answerinlinequery) answerInlineQuery query accepts array up to 50 results

But now this function doesn't accept an array https://github.com/Dolfik1/Funogram/blob/ac17d292222c04b7860c3a6cc6292099d158fd7f/src/Funogram.Telegram/Api.fs#L230

**Comment by Dolfik1** [comment]
Thank you for report. This issue was fixed in PR #28
