### ISSUE TITLE
Both test bots are now missing from github

### ISSUE THREAD

**Issue by megasuperlexa** [Dolfik1/Funogram#34]
Whatever happened to them?

**Comment by ForNeVeR** [comment]
Which ones? As I can see, `Funogram.TestBot` is still here: https://github.com/Dolfik1/Funogram/blob/fd4ae0b3e7655b4125fccd9481f393f38afd3d9c/src/Funogram.TestBot/Program.fs

**Comment by megasuperlexa** [comment]
Form r[eadme.md](https://github.com/Dolfik1/Funogram/blame/master/README.md#L43)
both links are 404 for me

**Comment by ForNeVeR** [comment]
cc @worldbeater: seems there was a link to your Memes.Bot, but now it's dead.
