### ISSUE TITLE
[Bug] Incorrect Bot command Handling

### ISSUE THREAD

**Issue by rami3l** [Dolfik1/Funogram#38]
The `getTextForCommand` function does not handle bot command correctly:

https://github.com/Dolfik1/Funogram/blob/fd4ae0b3e7655b4125fccd9481f393f38afd3d9c/src/Funogram.Telegram/Bot.fs#L27-L40

1. `/command@my_random_bot some arguments` will not work as expected as `@my_random_bot` is not at the end of the string.
2. `/command@my_random_bot @my_random_bot` will not work as expected as `@my_random_bot` is replaced twice.

**Comment by Dolfik1** [comment]
Thank you for report! It should be fixed in 4.4.2.6!
